# Generated by Django 4.2.16 on 2024-12-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_queue', '0002_user_is_password_changed_alter_user_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tasks',
            field=models.ManyToManyField(related_name='subjects', to='online_queue.task', verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_subjects', to='online_queue.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_queue.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_queue.subject', verbose_name='Предмет')),
            ],
            options={
                'unique_together': {('group', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subjects',
            field=models.ManyToManyField(related_name='groups', through='online_queue.GroupSubject', to='online_queue.subject', verbose_name='Предметы'),
        ),
    ]
