# Generated by Django 4.2.16 on 2024-12-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_queue', '0003_subject_tasks_alter_task_subject_groupsubject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tasks',
        ),
    ]
