# Generated by Django 4.2.16 on 2024-12-25 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_queue', '0004_remove_subject_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время постановки'),
            preserve_default=False,
        ),
    ]
