# Generated by Django 4.2.16 on 2024-12-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_queue', '0005_queue_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='position',
        ),
    ]
